In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [3]:
df

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369
...,...,...,...,...,...,...,...,...,...,...,...
9699,140,5.0,164.0,2981.107371,17.3,2013,Europe,Diesel,Front-wheel drive,NaN,15.101802
9700,180,NaN,154.0,2439.525729,15.0,2004,USA,Gasoline,All-wheel drive,0.0,17.962326
9701,220,2.0,138.0,2583.471318,15.1,2008,USA,Diesel,All-wheel drive,-1.0,17.186587
9702,230,4.0,177.0,2905.527390,19.4,2011,USA,Diesel,Front-wheel drive,1.0,15.331551


In [4]:
df.shape[0]

9704

In [5]:
df.fuel_type.nunique()

2

In [6]:
df.isnull().any().sum()

np.int64(4)

In [7]:
df[df['origin'] == 'Asia'].fuel_efficiency_mpg.max().round(2)

np.float64(23.76)

In [8]:
hp_med = df.horsepower.median()
hp_med

np.float64(149.0)

In [9]:
hp_mode = df.horsepower.mode()[0]
hp_mode

np.float64(152.0)

In [10]:
df['horsepower'] = df['horsepower'].fillna(hp_mode)
df['horsepower']

0       159.0
1        97.0
2        78.0
3       152.0
4       140.0
        ...  
9699    164.0
9700    154.0
9701    138.0
9702    177.0
9703    140.0
Name: horsepower, Length: 9704, dtype: float64

In [11]:
new_median = df['horsepower'].median()
new_median

np.float64(152.0)

In [12]:
x = df.loc[df['origin'] == 'Asia', ['vehicle_weight', 'model_year']].head(7).values

In [13]:
x

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

In [14]:
xt = np.transpose(x)
xt

array([[2714.21930965, 2783.86897424, 3582.68736772, 2231.8081416 ,
        2659.43145076, 2844.22753389, 3761.99403819],
       [2016.        , 2010.        , 2007.        , 2011.        ,
        2016.        , 2014.        , 2019.        ]])

In [15]:
xtx = xt @ x 
xtx

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

In [16]:
ixtx = np.linalg.inv(xtx)
ixtx

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

In [17]:
y = [1100, 1300, 800, 900, 1000, 1100, 1200]
y

[1100, 1300, 800, 900, 1000, 1100, 1200]

In [18]:
w = (ixtx @ xt) @ y
w

array([0.01386421, 0.5049067 ])

In [19]:
w.sum()

np.float64(0.5187709081074016)